### PR TITLE
Fixing breaking filepaths in setup.py

### PR DESCRIPTION
**Pull request by amrsoll**
Fixes https://github.com/gvalkov/setuptools-py2cfg/issues/12

### CODE REVIEW

**Comment by KOLANICH** [comment]
BTW, this project seems to be abandoned. My PRs are here for years untouched. I think we need a new maintainer for it.

**Comment by KOLANICH** [comment]
Also please remember that PEP 621 got implemented in `setuptools`, so I got rid of all `setup.cfg` in all my projects. I used `ini2toml` to convert.

**Comment by amrsoll** [comment]
I didn't know that, thank you for letting me know :) yet a new change in what the "pythony" way is :roll_eyes:

**Comment by gvalkov** [comment]
Hello @amrsoll and @KOLANICH. Thank you for your patches and sorry for the long time it took me to merge them. A new release on PyPi has been pushed with your changes.

**Pull request merged**
