### PR TITLE
Moved the metadata into PEP 621-compliant `pyproject.toml`

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by cclauss** [comment]
If you want to migrate `setup.cfg` into `pyproject.toml`, I would recommend using [`ini2toml`](https://pypi.org/project/ini2toml) to do the file conversion and running [`validate-pyproject`](https://github.com/abravalheri/validate-pyproject) to validate the results.  You will need to skip any configuration that is not yet PEP 621 compatible (e.g. flake8).

**Comment by KOLANICH** [comment]
>ini2toml

In fact I used it, with some manual postprocessing.

**Comment by KOLANICH** [comment]
@gvalkov

**Comment by gvalkov** [comment]
Thanks.

**Pull request closed without merging**
